export const customerFormContent = [
  {
    type: 'typography',
    text: 'Company Information',
    variant: 'h6',
    name: 'companyInformation',
    showOnStep: 0,
  },
  {
    type: 'text',
    label: 'Company Name',
    name: 'companyName',
    required: true,
    showOnStep: 0,
  },
  {
    type: 'text',
    label: 'Address',
    name: 'addressLineOne',
    required: true,
    showOnStep: 0,
  },
  {
    type: 'text',
    label: 'City',
    name: 'city',
    required: true,
    showOnStep: 0,
  },
  {
    type: 'select',
    label: 'State',
    name: 'state',
    required: true,
    options: ['USA', 'Canada', 'UK'],
    showOnStep: 0,
  },
  {
    type: 'text',
    label: 'Zip Code',
    name: 'zipCode',
    required: true,
    showOnStep: 0,
  },
  {
    type: 'typography',
    text: 'Primary Contact Information',
    variant: 'h6',
    name: 'primaryContactInformation',
    showOnStep: 1,
  },
  {
    type: 'text',
    label: 'First Name',
    name: 'primaryContactFirstName',
    required: true,
    showOnStep: 1,
  },
  {
    type: 'text',
    label: 'Last Name',
    name: 'primaryContactLastName',
    required: true,
    showOnStep: 1,
  },
  {
    type: 'typography',
    text: 'Accounts Payable Information',
    variant: 'h6',
    name: 'accountsPayableInformation',
    showOnStep: 2,
  },
  {
    type: 'text',
    label: 'First Name',
    name: 'accountsPayableFirstName',
    required: true,
    showOnStep: 2,
  },
  {
    type: 'text',
    label: 'Last Name',
    name: 'accountsPayableLastName',
    required: true,
    showOnStep: 2,
  },
];

export const contractorFormContent = [
  {
    type: 'typography',
    text: 'Company Information',
    variant: 'h6',
    name: 'companyInformation',
    showOnStep: 0,
  },
  {
    type: 'text',
    label: 'Company Name',
    name: 'companyName',
    required: true,
    showOnStep: 0,
  },
  {
    type: 'text',
    label: 'Address',
    name: 'addressLineOne',
    required: true,
    showOnStep: 0,
  },
  {
    type: 'text',
    label: 'City',
    name: 'city',
    required: true,
    showOnStep: 0,
  },
  {
    type: 'select',
    label: 'State',
    name: 'state',
    required: true,
    showOnStep: 0,
  },
  {
    type: 'text',
    label: 'Zip Code',
    name: 'zipCode',
    required: true,
    showOnStep: 0,
  },
  {
    type: 'typography',
    text: 'Primary Contact Information',
    variant: 'h6',
    name: 'primaryContactInformation',
    showOnStep: 1,
  },
  {
    type: 'text',
    label: 'First Name',
    name: 'primaryContactFirstName',
    required: true,
    showOnStep: 1,
  },
  {
    type: 'text',
    label: 'Last Name',
    name: 'primaryContactLastName',
    required: true,
    showOnStep: 1,
  },
  {
    type: 'typography',
    text: 'Dispatch Contact Information',
    variant: 'h6',
    name: 'dispatchContactInformation',
    showOnStep: 2,
  },
  {
    type: 'text',
    label: 'First Name',
    name: 'dispatchContactFirstName',
    required: true,
    showOnStep: 2,
  },
  {
    type: 'text',
    label: 'Last Name',
    name: 'dispatchContactLastName',
    required: true,
    showOnStep: 2,
  },
];
